### ISSUE TITLE
[bug] wxwork-gpt-api AxiosError: Request failed with status code 500 at settle (/app/node_modules/axios/dist/node/axios.cjs:1855:12) at IncomingMessage.handleStreamEnd (/app/node_modules/axi

### ISSUE THREAD

**Issue by lofter414** [labring/laf#1180]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

https://laf.run

### What happened

Time: 2023-05-28 02:23:13
Request ID: 658c2325-e020-4ee8-87e0-718d1bfbfa09
Function: wxwork-gpt-api
Content:
AxiosError: Request failed with status code 500
    at settle (/app/node_modules/axios/dist/node/axios.cjs:1855:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:2712:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_RESPONSE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {

### How to reproduce

wxwork-gpt-api
AxiosError: Request failed with status code 500 at settle (/app/node_modules/axios/dist/node/axios.cjs:1855:12) at IncomingMessage.handleStreamEnd (/app/node_modules/axi

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by skyoct** [comment]
@lofter414 Please use gpt in laf.dev

**Comment by lofter414** [comment]
Time: 2023-06-06 01:16:13
Request ID: 325d7823-926a-4a8f-9282-f5beaf333139
Function: wxwork-gpt-api
Content:
TypeError: Cannot read properties of undefined (reading 'expires')
    at getToken (evalmachine.<anonymous>:12:48)
    at sendMessage (evalmachine.<anonymous>:35:33)
    at asyncSendMessage (evalmachine.<anonymous>:44:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default_1 (evalmachine.<anonymous>:34:5)
    at async FunctionEngine.run (/app/dist/support/function-engine/engine.js:34:24)
    at async CloudFunction.invoke (/app/dist/support/function-engine/function.js:73:23)
    at async handleInvokeFunction (/app/dist/handler/invoke-func.js:59:24) undefined
