### ISSUE TITLE
[bug] laf-server CrashLoopBackOff  ARM Linux

### ISSUE THREAD

**Issue by GeekWorkCode** [labring/laf#1427]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux (self-host)

### What happened

环境信息 ：sealos version      
CriVersionInfo:
  RuntimeApiVersion: v1
  RuntimeName: containerd
  RuntimeVersion: v1.6.21
  Version: 0.1.0
KubernetesVersionInfo:
  clientVersion:
    buildDate: "2022-12-08T10:15:09Z"
    compiler: gc
    gitCommit: 9710807c82740b9799453677c977758becf0acbb
    gitTreeState: clean
    gitVersion: v1.24.9
    goVersion: go1.18.9
    major: "1"
    minor: "24"
    platform: linux/arm64
  kustomizeVersion: v4.5.4
  serverVersion:
    buildDate: "2022-12-08T10:08:06Z"
    compiler: gc
    gitCommit: 9710807c82740b9799453677c977758becf0acbb
    gitTreeState: clean
    gitVersion: v1.24.9
    goVersion: go1.18.9
    major: "1"
    minor: "24"
    platform: linux/arm64
SealosVersion:
  buildDate: "2023-04-23T14:23:15Z"
  compiler: gc
  gitCommit: f696a621
  gitVersion: 4.2.0
  goVersion: go1.20.3
  platform: linux/arm64

错误日志
kubectl logs -f laf-server-6d5c6fb88c-nf59h  -n laf-system
/app/node_modules/sharp/lib/sharp.js:37
  throw new Error(help.join('\n'));
  ^

Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-arm64v8.node'
Require stack:
- /app/node_modules/sharp/lib/sharp.js
- /app/node_modules/sharp/lib/constructor.js
- /app/node_modules/sharp/lib/index.js
- /app/dist/user/user.service.js
- /app/dist/user/user.module.js
- /app/dist/authentication/authentication.module.js
- /app/dist/app.module.js
- /app/dist/main.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-arm64v8 runtime: "npm install --platform=linux --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/app/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.16.1

### How to reproduce

ARM Linux
cd deploy

# replace with your domain here.
export DOMAIN=域名.com

# install k8s cluster
sh install-on-linux.sh $DOMAIN

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by GeekWorkCode** [comment]
1.0.0-beta.10报这个错，试了1.0.0-beta.9可运行
