### ISSUE TITLE
[Docker-Compose部署问题]修改域名 做好泛解析之后 想要套一层反代实现https 网页访问显示404

### ISSUE THREAD

**Issue by licsber** [labring/laf#273]
我的步骤：
```bash
git clone xxx
cd laf/deploy/docker-compose
vim .env # 修改

DEPLOY_DOMAIN=sls.example.com
SYS_CLIENT_HOST=console.sls.example.com
OSS_DOMAIN=oss.sls.example.com

sudo docker-compose up
```
域名对于sls.example.com和*.sls.example.com均解析到了服务器
但是服务器有防火墙 对外只开放了443端口
我配置sls.example.com和*.sls.example.com均转发（反向代理）到服务器内网ip:10.0.8.8的8000端口

网页访问显示如下：
```text
{"error_msg":"404 Route Not Found"}
```
想问一下还有其他端口也需要暴露出来么 或者修改什么选项？

查了一下 应该是apisix报的 暂时没找到解决方案 故此issue

后台日志如下：
```text
mongo_1                   | {"t":{"$date":"2022-08-17T01:35:33.894+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":"[1660700133:894030][1:0x7fcaba0b3700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 56, snapshot max: 56 snapshot count: 0, oldest timestamp: (1660699824, 1) , meta checkpoint timestamp: (1660700124, 1) base write gen: 49"}}

gateway_1                 | 192.168.64.1 - - [17/Aug/2022:01:35:54 +0000] console.sls.example.com "GET / HTTP/1.1" 404 47 0.000 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15" - - - "http://console.sls.example.com"
```

**Comment by maslow** [comment]
有没有其它报错信息

**Comment by licsber** [comment]
1. 已更新镜像版本 并使用`sudo docker-compose down -v`清除旧volume
目前测试版本：
```text
               Container                          Repository                Tag          Image Id       Size  
--------------------------------------------------------------------------------------------------------------
docker-compose_apisix-dashboard_1         apache/apisix-dashboard      2.13-alpine     712ac4ecc93e   109.3 MB
docker-compose_app-console_1              lafyun/app-console           latest          fc18a909b744   200.9 MB
docker-compose_etcd_1                     quay.io/coreos/etcd          v3.5.4          77b8864f9930   181.5 MB
docker-compose_gateway-controller_1       lafyun/gateway-controller    latest          2ca2a60a5df8   185.1 MB
docker-compose_gateway_1                  apache/apisix                2.14.1-alpine   382ae3df093d   148 MB  
docker-compose_instance-controller_1      lafyun/instance-controller   latest          88faea19651a   206.9 MB
docker-compose_mongo_1                    bitnami/mongodb              5.0.8           3df99ef70877   627.9 MB
docker-compose_oss_1                      bitnami/minio                2022.8.11       5516aa3d5d08   243.7 MB
docker-compose_pull-app-service-image_1   lafyun/app-service           latest          97954f74288d   449.7 MB
docker-compose_system-client_1            lafyun/system-client         latest          fe7bc6d0749d   192.2 MB
docker-compose_system-server_1            lafyun/system-server         latest          ebf09cfc5fe6   252.3 MB
```
仍旧是`{"error_msg":"404 Route Not Found"}`
关于其他的报错信息 这个配置和不配置自定义域名好像都会出现 我就没贴在issue里：
```text
system-server_1           | 2022/08/16 23:04:49 Connected to tcp://mongo:27017
system-server_1           | ****** init start ******
system-server_1           | [2022-08-16T23:04:49.877] [INFO] server - server logging level is DEBUG
system-server_1           | [2022-08-16T23:04:49.897] [INFO] accessor:sys_db - accessor:sys_db logging level is DEBUG
system-server_1           | [2022-08-16T23:04:49.897] [INFO] accessor:sys_db - mongo accessor connecting...
system-server_1           | [2022-08-16T23:04:51.979] [INFO] accessor:sys_db - mongo accessor connected, db: sys_db
system-server_1           | [2022-08-16T23:04:51.984] [INFO] server - db:sys_db connected
system-server_1           | [2022-08-16T23:04:52.104] [INFO] server - create system collection indexes
system-server_1           | [2022-08-16T23:04:52.113] [INFO] server - create root account
system-server_1           | node:internal/errors:464
system-server_1           |     ErrorCaptureStackTrace(err);
system-server_1           |     ^
system-server_1           | 
system-server_1           | TypeError [ERR_INVALID_URL]: Invalid URL
system-server_1           |     at new NodeError (node:internal/errors:371:5)
system-server_1           |     at onParseError (node:internal/url:552:9)
system-server_1           |     at new URL (node:internal/url:628:5)
system-server_1           |     at Function.get MINIO_CONFIG [as MINIO_CONFIG] (/app/dist/config.js:71:35)
system-server_1           |     at MinioAgent.mc_set_alias (/app/dist/support/minio.js:170:45)
system-server_1           |     at Function.New (/app/dist/support/minio.js:27:18)
system-server_1           |     at Function.initAppOSSUserPolicy (/app/dist/support/initializer.js:111:46)
system-server_1           |     at main (/app/dist/init.js:22:37)
system-server_1           |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
system-server_1           |   input: 'oss.127-0-0-1.nip.io',
system-server_1           |   code: 'ERR_INVALID_URL'
system-server_1           | }
system-server_1           | ****** init end *******
system-server_1           | ****** start service: node ./dist/index.js *******
```
2. 我使用traefik管理ssl证书 反向代理 代理到后者（laf的https监听端口）的话会报400
The plain HTTP request was sent to HTTPS port
这个报错是由openresty发出的 所以应该是代理到8000端口才是正确的

3. 9000端口可以访问 但是它的默认密码在哪呢 （我好像没有找到

**Comment by licsber** [comment]
补充一下从启动到结束 system-server的日志
```text
Attaching to docker-compose_system-server_1
system-server_1           | 2022/08/18 00:55:47 Waiting for: tcp://mongo:27017
system-server_1           | 2022/08/18 00:55:47 Waiting for: http://oss:9001
system-server_1           | 2022/08/18 00:55:47 Problem with dial: dial tcp 192.168.64.4:27017: connect: connection refused. Sleeping 1s
system-server_1           | 2022/08/18 00:55:47 Problem with request: Get http://oss:9001: dial tcp 192.168.64.7:9001: connect: connection refused. Sleeping 1s
system-server_1           | 2022/08/18 00:55:48 Problem with dial: dial tcp 192.168.64.4:27017: connect: connection refused. Sleeping 1s
system-server_1           | 2022/08/18 00:55:48 Received 200 from http://oss:9001
system-server_1           | 2022/08/18 00:55:49 Problem with dial: dial tcp 192.168.64.4:27017: connect: connection refused. Sleeping 1s
system-server_1           | 2022/08/18 00:55:50 Problem with dial: dial tcp 192.168.64.4:27017: connect: connection refused. Sleeping 1s
system-server_1           | 2022/08/18 00:55:51 Problem with dial: dial tcp 192.168.64.4:27017: connect: connection refused. Sleeping 1s
system-server_1           | 2022/08/18 00:55:52 Problem with dial: dial tcp 192.168.64.4:27017: connect: connection refused. Sleeping 1s
system-server_1           | 2022/08/18 00:55:53 Problem with dial: dial tcp 192.168.64.4:27017: connect: connection refused. Sleeping 1s
system-server_1           | 2022/08/18 00:55:54 Problem with dial: dial tcp 192.168.64.4:27017: connect: connection refused. Sleeping 1s
system-server_1           | 2022/08/18 00:55:55 Connected to tcp://mongo:27017
system-server_1           | ****** init start ******
system-server_1           | [2022-08-18T00:55:56.775] [INFO] server - server logging level is DEBUG
system-server_1           | [2022-08-18T00:55:56.786] [INFO] accessor:sys_db - accessor:sys_db logging level is DEBUG
system-server_1           | [2022-08-18T00:55:56.786] [INFO] accessor:sys_db - mongo accessor connecting...
system-server_1           | [2022-08-18T00:55:59.755] [INFO] accessor:sys_db - mongo accessor connected, db: sys_db
system-server_1           | [2022-08-18T00:55:59.759] [INFO] server - db:sys_db connected
system-server_1           | [2022-08-18T00:56:00.009] [INFO] server - create system collection indexes
system-server_1           | [2022-08-18T00:56:00.019] [INFO] server - create root account
system-server_1           | [2022-08-18T00:56:00.527] [INFO] server - init app user policy
system-server_1           | [2022-08-18T00:56:02.260] [INFO] server - create builtin specs
system-server_1           | [2022-08-18T00:56:02.606] [INFO] server - create system extension server app
system-server_1           | [2022-08-18T00:56:02.613] [INFO] server - start system extension server app
system-server_1           | ****** init end *******
system-server_1           | ****** start service: node ./dist/index.js *******
system-server_1           | [2022-08-18T00:56:03.214] [INFO] server - server logging level is DEBUG
system-server_1           | [2022-08-18T00:56:03.226] [INFO] accessor:sys_db - accessor:sys_db logging level is DEBUG
system-server_1           | [2022-08-18T00:56:03.226] [INFO] accessor:sys_db - mongo accessor connecting...
system-server_1           | [2022-08-18T00:56:03.874] [INFO] server - listened on 9000
system-server_1           | [2022-08-18T00:56:03.899] [INFO] accessor:sys_db - mongo accessor connected, db: sys_db
system-server_1           | [2022-08-18T00:56:03.900] [INFO] server - db:sys_db connected
system-server_1           | 2022/08/18 00:56:48 Received signal: terminated
system-server_1           | [2022-08-18T00:56:48.369] [INFO] server - exiting: closing db connection
system-server_1           | [2022-08-18T00:56:48.374] [INFO] accessor:sys_db - mongo connection closed
system-server_1           | [2022-08-18T00:56:48.374] [INFO] server - process gracefully exited!
system-server_1           | 2022/08/18 00:56:48 Command finished successfully.
docker-compose_system-server_1 exited with code 0
```

**Comment by maslow** [comment]
```
docker-compose_system-server_1            lafyun/system-server         latest          ebf09cfc5fe6   252.3 MB
```

我看到这个服务的 镜像 ID 是 `ebf09cfc5fe6`， 这个不是最新版的镜像的 ID，我怀疑是使用了 docker hub mirror 缓存的结果。

再提供一下 `docker images` 的信息，或者直接指定具体镜像版本：https://hub.docker.com/repository/docker/lafyun/system-server

```
system-server_1           | node:internal/errors:464
system-server_1           |     ErrorCaptureStackTrace(err);
system-server_1           |     ^
system-server_1           | 
system-server_1           | TypeError [ERR_INVALID_URL]: Invalid URL
system-server_1           |     at new NodeError (node:internal/errors:371:5)
system-server_1           |     at onParseError (node:internal/url:552:9)
system-server_1           |     at new URL (node:internal/url:628:5)
system-server_1           |     at Function.get MINIO_CONFIG [as MINIO_CONFIG] (/app/dist/config.js:71:35)
system-server_1           |     at MinioAgent.mc_set_alias (/app/dist/support/minio.js:170:45)
system-server_1           |     at Function.New (/app/dist/support/minio.js:27:18)
system-server_1           |     at Function.initAppOSSUserPolicy (/app/dist/support/initializer.js:111:46)
system-server_1           |     at main (/app/dist/init.js:22:37)
system-server_1           |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
system-server_1           |   input: 'oss.127-0-0-1.nip.io',
system-server_1           |   code: 'ERR_INVALID_URL'
system-server_1           | }
```

这个报错，在最新版 [0.8.7-alpha.2](https://hub.docker.com/layers/273442911/lafyun/system-server/0.8.7-alpha.2/images/sha256-828533c66c61f5bc09ad265a811c28c0d5cbe3a15742544f551fcd40ced32c9e?context=repo)已经修复了。

**Comment by licsber** [comment]
好的 谢谢 已更新最新版镜像
目前console已可网页访问
此issue结束

贴一下我的反代设置吧
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: laf

---
apiVersion: v1
kind: Service
metadata:
  name: laf-service
  namespace: laf
spec:
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  name: laf-service
  namespace: laf
subsets:
  - addresses:
      - ip: 10.0.8.8
    ports:
      - port: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laf-ingress
  namespace: laf
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: cloudflare-prod-cluster-issuer
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-cors@kubernetescrd
spec:
  rules:
  - host: sls.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: laf-service
              port:
                number: 80
  - host: '*.sls.example.com'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: laf-service
              port:
                number: 80
  tls:
    - hosts:
      - sls.example.com
      - '*.sls.example.com'
      secretName: sls-example-com-tls
```

**Comment by maslow** [comment]
laf 支持直接部署在 k8s 集群上

**Comment by licsber** [comment]
> laf 支持直接部署在 k8s 集群上

知道的 不过我目前只需要单机跑个测试 还没想放到集群上
而且像是mongo和minio这两个东西最好还是独立部署 也不放集群上调度 所以我目前用不到

**Comment by licsber** [comment]
倒是提议作者可以增加一个配置项
就像是Cloudreve的站点URL
或者前端识别一下当前访问的URL

以智能替换前端里生成的各种地址 （识别反代环境）
如前端里 http://qliawf.sls.example.com:8000/index
但我实际访问的应该是 https://qliawf.sls.example.com/index
即更改了http为https 同时去掉端口号这种情况

**Comment by maslow** [comment]
有考虑到以下情况：
1. app / oss 访问地址 是可以不同于 console 的
2. app 和 oss 访问地址 也未必是一致的， oss 也可能是用别的顶级域名
3. 尤其是后续增加 多可用区的支持， apps 、 laf sys 、oss 都是分配 各自的域名、各自的代理和可用区

**Comment by licsber** [comment]
> apps 、 laf sys 、oss 都是分配 各自的域名、各自的代理和可用区

懂了 那逻辑应该是在apps的配置文件里增加这些
