### ISSUE TITLE
云函数返回axios的response报错500

### ISSUE THREAD

**Issue by Zing22** [labring/laf#280]
问题描述：
1. 云函数调试后，无日志产生，看网络请求报500错误

复现代码块：
```js
import axios from 'axios';

exports.main = async function (ctx: FunctionContext) {
  return await axios.post("https://api.weixin.qq.com/wxa/msg_sec_check");
}
```

容器日志：
```
[2022-08-19T13:32:15.644] [ERROR] server - dfd1ee4e-bf31-4eca-b856-3e62c8693732 failed to invoke error Error: cyclic dependency detected
    at new BSONError (/app/node_modules/bson/lib/error.js:23:42)
    at serializeObject (/app/node_modules/bson/lib/parser/serializer.js:267:19)
    at serializeInto (/app/node_modules/bson/lib/parser/serializer.js:815:25)
    at serializeObject (/app/node_modules/bson/lib/parser/serializer.js:280:20)
    at serializeInto (/app/node_modules/bson/lib/parser/serializer.js:815:25)
    at serializeObject (/app/node_modules/bson/lib/parser/serializer.js:280:20)
    at serializeInto (/app/node_modules/bson/lib/parser/serializer.js:815:25)
    at serializeObject (/app/node_modules/bson/lib/parser/serializer.js:280:20)
    at serializeInto (/app/node_modules/bson/lib/parser/serializer.js:815:25)
    at serializeObject (/app/node_modules/bson/lib/parser/serializer.js:280:20)
```

问题定位（from 马哥）：
* 看你发的日志， 是 将 函数执行结果 入 log 库的时候， bson 序列化时 遇到了 js 对象的循环引用， 异常了。
* 你先别 直接返回 response 对象了， 返回 response.data 吧

初步修复代码：
```js
import axios from 'axios';

exports.main = async function (ctx: FunctionContext) {
  const rsp = await axios.post("https://api.weixin.qq.com/wxa/msg_sec_check");
  return rsp.data;
}
```

**Comment by maslow** [comment]
大概推测，应该是由于返回了 response 对象，将此结果写日志时， 进行了 bson 序列化操作，循环引用导致的异常。

很快会重构云函数日志，到时候会一并处理掉此问题。
