### ISSUE TITLE
构建oss对象endPoint不允许http/https/端口？

### ISSUE THREAD

**Issue by hankeke** [labring/laf#327]
### 代码
```js
import cloud from '@/cloud-sdk'

exports.main = async function (ctx: FunctionContext) {
  const { bucketName, fileName } = ctx.body
  const Minio = require('minio')

  const oss = new Minio.Client({
    endPoint: cloud.env.OSS_EXTERNAL_ENDPOINT,
    useSSL: true,
    accessKey: cloud.env.OSS_ACCESS_KEY,
    secretKey: cloud.env.OSS_ACCESS_SECRET,
    region: cloud.env.OSS_REGION
  });
  return await oss.presignedUrl('PUT', bucketName, fileName, 3600)
}
```
### 日志
```
- [2022/09/19 14:20:22] - Invalid endPoint : https://oss.lafyun.com
- [2022/09/19 14:20:22] - InvalidEndpointError: Invalid endPoint : https://oss.lafyun.com
    at new Client (/app/node_modules/minio/dist/main/minio.js:102:13)
    at exports.main (CloudFunction.get-upload-oss-uri:8:17)
    at CloudFunction.get-upload-oss-uri:27:7
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at FunctionEngine.run (/app/dist/support/function-engine/engine.js:33:35)
    at CloudFunction.invoke (/app/dist/support/function-engine/function.js:62:36)
    at handleDebugFunction (/app/dist/handler/debug-func.js:44:35)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
```
### 备注

- endpoint 不允许 `http` 或者 `https` 开头
- endpoint 不允许域名中出现端口 例如 `oss.lafyun.com:8848`

**Comment by skyoct** [comment]
https://docs.min.io/docs/javascript-client-quickstart-guide.html

**Comment by maslow** [comment]
```js
var Minio = require('minio')

var minioClient = new Minio.Client({
    endPoint: 'play.min.io',
    port: 9000,
    useSSL: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});
```

@see https://docs.min.io/docs/javascript-client-quickstart-guide.html
