### ISSUE TITLE
server - waiting for db connected...

### ISSUE THREAD

**Issue by wxiubin** [labring/laf#345]
```
gateway-controller_1      | [2022-09-25T04:46:33.390] [INFO] server - waiting for db connected...
gateway-controller_1      | [2022-09-25T04:46:34.342] [ERROR] server - db:sys_db connect failed MongoServerSelectionError: connect ECONNREFUSED 172.18.0.11:27017
gateway-controller_1      |     at Timeout._onTimeout (/app/node_modules/mongodb/lib/sdam/topology.js:325:38)
gateway-controller_1      |     at listOnTimeout (node:internal/timers:559:17)
gateway-controller_1      |     at processTimers (node:internal/timers:502:7) {
gateway-controller_1      |   reason: TopologyDescription {
gateway-controller_1      |     type: 'ReplicaSetNoPrimary',
gateway-controller_1      |     servers: Map(1) { 'mongo:27017' => [ServerDescription] },
gateway-controller_1      |     stale: false,
gateway-controller_1      |     compatible: true,
gateway-controller_1      |     heartbeatFrequencyMS: 10000,
gateway-controller_1      |     localThresholdMS: 15,
gateway-controller_1      |     setName: 'laf',
gateway-controller_1      |     logicalSessionTimeoutMinutes: undefined
gateway-controller_1      |   }
gateway-controller_1      | }
gateway-controller_1      |
gateway-controller_1      | > gateway-controller@0.8.7-alpha.3 start
gateway-controller_1      | > node ./dist/index.js
gateway-controller_1      |
gateway-controller_1      | [2022-09-25T04:46:39.833] [INFO] server - server logging level is DEBUG
gateway-controller_1      | [2022-09-25T04:46:40.043] [INFO] server - start init base route
gateway-controller_1      | [2022-09-25T04:46:40.058] [INFO] server - start scheduler loop
gateway-controller_1      | [2022-09-25T04:46:40.063] [INFO] server - listened on 9001
gateway-controller_1      | [2022-09-25T04:46:40.083] [INFO] server - create route successful
gateway-controller_1      | [2022-09-25T04:46:40.256] [INFO] server - create route successful
gateway-controller_1      | [2022-09-25T04:46:40.319] [INFO] server - create route successful
gateway-controller_1      | [2022-09-25T04:46:40.320] [INFO] server - create route successful
gateway-controller_1      | [2022-09-25T04:46:40.321] [INFO] server - create route successful
gateway-controller_1      | [2022-09-25T04:46:41.060] [INFO] server - waiting for db connected...
gateway-controller_1      | [2022-09-25T04:46:42.061] [INFO] server - waiting for db connected...
gateway-controller_1      | [2022-09-25T04:46:43.061] [INFO] server - waiting for db connected...
gateway-controller_1      | [2022-09-25T04:46:44.062] [INFO] server - waiting for db connected...
gateway-controller_1      | [2022-09-25T04:46:45.063] [INFO] server - waiting for db connected...
gateway-controller_1      | [2022-09-25T04:46:46.063] [INFO] server - waiting for db connected...
gateway-controller_1      | [2022-09-25T04:46:47.064] [INFO] server - waiting for db connected...
gateway-controller_1      | [2022-09-25T04:46:48.064] [INFO] server - waiting for db connected...
gateway-controller_1      | [2022-09-25T04:46:49.064] [INFO] server - waiting for db connected...
docker-compose_gateway-controller_1 exited with code 137
system-server_1           | 2022/09/25 04:47:03 Timeout after 1m0s waiting on dependencies to become available: [tcp://mongo:27017 http://oss:9001]
system-server_1           | 2022/09/25 04:47:07 Problem with dial: dial tcp: lookup mongo on 127.0.0.11:53: no such host. Sleeping 1s
system-server_1           | 2022/09/25 04:47:08 Problem with dial: dial tcp: lookup mongo on 127.0.0.11:53: no such host. Sleeping 1s
system-server_1           | 2022/09/25 04:47:09 Problem with dial: dial tcp: lookup mongo on 127.0.0.11:53: no such host. Sleeping 1s
```

**Comment by wxiubin** [comment]
```
$ docker-compose logs -f mongo
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 189, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[17309] Failed to execute script docker-compose
```

**Comment by maslow** [comment]
`PermissionError: [Errno 13] Permission denied` 
这个应该是没权限执行

**Comment by wxiubin** [comment]
> `PermissionError: [Errno 13] Permission denied` 这个应该是没权限执行

上面的记录改为了 我加了 sudo 执行之后 的结果

**Comment by maslow** [comment]
👌 看到日志是 mongo 没启来， 可能你要排查一下 mongo 的这个错误来源，根据我的经验可能和你的环境相关：
1. cpu 架构和型号发一下，确认是 mongo 支持的处理器（bitnami/mongo 镜像不支持 arm 和 较老的 x86）

**Comment by wxiubin** [comment]
> 👌 看到日志是 mongo 没启来， 可能你要排查一下 mongo 的这个错误来源，根据我的经验可能和你的环境相关：
> 
> 1. cpu 架构和型号发一下，确认是 mongo 支持的处理器（bitnami/mongo 镜像不支持 arm 和 较老的 x86）

cpu 是 j4025，系统是群晖 nas 的 dsm7，应该是基于 FreeBSD

**Comment by maslow** [comment]
MongoDB requires the following minimum x86_64 microarchitectures:

For Intel x86_64, MongoDB requires Sandy Bridge or later.
For AMD x86_64, MongoDB requires Bulldozer or later.

https://jira.mongodb.org/browse/DOCS-14684
https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610

https://www.intel.com/content/www/us/en/products/sku/197307/intel-celeron-processor-j4025-4m-cache-up-to-2-90-ghz/specifications.html


你这款处理器比较老， mongodb 5.0 要求处理器支持 avx （sandy bridge AVX）能力。可以看上面我帮你找的链接参考。

可以改成 mongodb 4.4.13 尝试一下
