### ISSUE TITLE
[Question] Cloud function execution reported an error: Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by syrm-ll** [labring/laf#828]
### Search before asking

- [X] I had searched in the [issues](https://github.com/labring/laf/issues?q=is%3Aissue) and found no similar issues.

### Question

Sample code:
```ts
import cloud from '@lafjs/cloud'
import { ChatGPTUnofficialProxyAPI } from 'chatgpt'

export async function main(ctx: FunctionContext) {
  const api = new ChatGPTUnofficialProxyAPI({ accessToken: '<TOKEN>' })
  const res = await api.sendMessage('')
  return res
}
```

An error occurred when trying to run:
```log
[2023-02-27 11:10:47]
'require() of ES Module /app/node_modules/chatgpt/build/index.js from /app/dist/support/function-engine/function.js not supported.\n' +
  'Instead change the require of index.js in /app/dist/support/function-engine/function.js to a dynamic import() which is available in all CommonJS modules.' '/app/dist/support/function-engine/function.js:27\n' +
  '        return require(module);\n' +
  '               ^\n' +
  '\n' +
  'Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/chatgpt/build/index.js from /app/dist/support/function-engine/function.js not supported.\n' +
  'Instead change the require of index.js in /app/dist/support/function-engine/function.js to a dynamic import() which is available in all CommonJS modules.\n' +
  '    at require_func (/app/dist/support/function-engine/function.js:27:16)\n' +
  '    at CloudFunction.private-test-package:5:19\n' +
  '    at Script.runInContext (node:vm:141:12)\n' +
  '    at Script.runInNewContext (node:vm:146:17)\n' +
  '    at FunctionEngine.run (/app/dist/support/function-engine/engine.js:40:35)\n' +
  '    at CloudFunction.invoke (/app/dist/support/function-engine/function.js:84:36)\n' +
  '    at handleDebugFunction (/app/dist/handler/debug-func.js:61:35)\n' +
  '    at handleInvokeFunction (/app/dist/handler/invoke-func.js:28:59)'
```

## question
This seems to be a node execution environment problem? I may need to change 'package. json'? But laf does not provide similar options

**Comment by maslow** [comment]
Known issue, please reference  https://github.com/labring/laf/pull/819

**Comment by hankeke** [comment]
see https://github.com/labring/laf/pull/819
