### ISSUE TITLE
deno support?

### ISSUE THREAD

**Issue by git136975643** [labring/laf#89]
error: Uncaught TypeError: t is not a function
    at Fe.exports (https://cdn.esm.sh/v78/axios@0.21.4/es2022/axios.js:3:5205)
    at O.request (https://cdn.esm.sh/v78/axios@0.21.4/es2022/axios.js:3:10754)
    at O.<computed> [as post] (https://cdn.esm.sh/v78/axios@0.21.4/es2022/axios.js:3:11208)
    at Function.post (https://cdn.esm.sh/v78/axios@0.21.4/es2022/axios.js:2:742)
    at a.<anonymous> (https://cdn.esm.sh/v78/laf-client-sdk@0.7.11/es2022/laf-client-sdk.js:2:2439)
    at c (https://cdn.esm.sh/v78/laf-client-sdk@0.7.11/es2022/laf-client-sdk.js:2:1460)
    at Object.next (https://cdn.esm.sh/v78/laf-client-sdk@0.7.11/es2022/laf-client-sdk.js:2:764)
    at https://cdn.esm.sh/v78/laf-client-sdk@0.7.11/es2022/laf-client-sdk.js:2:490
    at new Promise (<anonymous>)
    at m (https://cdn.esm.sh/v78/laf-client-sdk@0.7.11/es2022/laf-client-sdk.js:2:287)

麻烦客户端支持下deno，esm

**Comment by git136975643** [comment]
// import * as a from "https://esm.sh/laf-client-sdk"
import * as LaF from "https://cdn.esm.sh/v78/laf-client-sdk@0.7.11/es2022/laf-client-sdk.js"
